apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: login
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: login
    spec:
      containers:
      - name: login
        image: janajohny/simple:v2
        imagePullPolicy: Always
        env:
        - name: MYSQL_USER
          value: login
        - name: MYSQL_PASSWORD
          value: login
        - name: MYSQL_DATABASE
          value: login_system
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-deployment:3306/login_system
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: login
  name: login
spec:
  ports:
  - name: login
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: login

