image:
  repository: mysql
  tag: "5.7"
  pullPolicy: IfNotPresent

mysqlRootPassword: password
mysqlDatabase: codejavadb
mysqlUser: code
mysqlPassword: code

service:
  type: ClusterIP
  port: 3306

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
