apiVersion: v1
kind: Service
metadata:
  name: mysql-deployment
  labels:
    app: mysql-deployment
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
  selector:
    app: mysql-deployment

